# Lab 6: Trino SQL Engine - Distributed Query Engine

## üéØ Objectives
- Understand Trino SQL engine architecture
- Learn to query multiple data sources with SQL
- Practice federated queries across databases
- Implement data lakehouse analytics
- Optimize query performance

## üìã Prerequisites
- Complete Labs 1-5
- All database containers are running
- Sample data is loaded
- Basic SQL knowledge

## üèóÔ∏è Architecture Overview
Trino is a distributed SQL query engine designed to query large datasets distributed over one or more heterogeneous data sources. It allows you to:
- Query data from multiple sources with a single SQL statement
- Perform federated queries across different databases
- Access data lakes and data warehouses
- Scale horizontally for high performance

## üìä Use Case: Multi-Source Analytics Platform
We'll build an analytics platform that can query:
- **MongoDB** (Document Store) - Product catalog
- **Neo4j** (Graph Database) - User relationships  
- **Redis** (Key-Value Store) - Session data
- **PostgreSQL** (Relational) - Order transactions
- **CSV Files** (Data Lake) - Historical data

In [1]:
# Install Trino Python client
%pip install trino

# Import required libraries
import trino
import pandas as pd
import json
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns

print("‚úÖ Trino client installed successfully!")

# Real Trino Connection Setup
# Uncomment the following lines to connect to a real Trino cluster

"""
# Connect to Trino cluster
conn = trino.dbapi.connect(
    host='localhost',
    port=8080,
    user='admin',
    catalog='mongodb',  # Default catalog
    schema='ecommerce'   # Default schema
)

# Test connection
cursor = conn.cursor()
cursor.execute('SELECT 1')
result = cursor.fetchone()
print(f"‚úÖ Connected to Trino cluster! Test query result: {result}")
"""

print("üìù Note: To use real Trino, uncomment the connection code above")
print("üìù For now, we'll use a simulator to demonstrate concepts")

Requirement already satisfied: trino in /Users/trungtv/miniforge3/envs/datalab/lib/python3.10/site-packages (0.336.0)
Requirement already satisfied: lz4 in /Users/trungtv/miniforge3/envs/datalab/lib/python3.10/site-packages (from trino) (4.4.4)
Requirement already satisfied: orjson>=3.11.0 in /Users/trungtv/miniforge3/envs/datalab/lib/python3.10/site-packages (from trino) (3.11.3)
Requirement already satisfied: python-dateutil in /Users/trungtv/miniforge3/envs/datalab/lib/python3.10/site-packages (from trino) (2.9.0.post0)
Requirement already satisfied: pytz in /Users/trungtv/miniforge3/envs/datalab/lib/python3.10/site-packages (from trino) (2025.2)
Requirement already satisfied: requests>=2.32.4 in /Users/trungtv/miniforge3/envs/datalab/lib/python3.10/site-packages (from trino) (2.32.5)
Requirement already satisfied: tzlocal in /Users/trungtv/miniforge3/envs/datalab/lib/python3.10/site-packages (from trino) (5.3.1)
Requirement already satisfied: zstandard in /Users/trungtv/miniforge3/envs/datalab/lib/python3.10/site-packages (from trino) (0.25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/trungtv/miniforge3/envs/datalab/lib/python3.10/site-packages (from requests>=2.32.4->trino) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /Users/trungtv/miniforge3/envs/datalab/lib/python3.10/site-packages (from requests>=2.32.4->trino) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/trungtv/miniforge3/envs/datalab/lib/python3.10/site-packages (from requests>=2.32.4->trino) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/trungtv/miniforge3/envs/datalab/lib/python3.10/site-packages (from requests>=2.32.4->trino) (2025.8.3)
Requirement already satisfied: six>=1.5 in /Users/trungtv/miniforge3/envs/datalab/lib/python3.10/site-packages (from python-dateutil->trino) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
‚úÖ Trino client installed successfully!
üìù Note: To use real Trino, uncomment the connection code above
üìù For now, we'll use a simulator to demonstrate concepts

In [2]:
# Real Trino Connection Setup
# Connect to actual Trino cluster

import trino
import pandas as pd
import json
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns

class TrinoClient:
    """
    Real Trino client for connecting to Trino cluster
    """
    
    def __init__(self, host='localhost', port=8080, user='admin'):
        self.host = host
        self.port = port
        self.user = user
        self.conn = None
    
    def connect(self):
        """Connect to Trino cluster"""
        try:
            self.conn = trino.dbapi.connect(
                host=self.host,
                port=self.port,
                user=self.user,
                catalog='mongodb',  # Default catalog
                schema='ecommerce'   # Default schema
            )
            print(f"‚úÖ Connected to Trino cluster at {self.host}:{self.port}")
            return True
        except Exception as e:
            print(f"‚ùå Failed to connect to Trino: {e}")
            print("üìù Make sure Trino cluster is running with: docker-compose -f docker-compose-trino.yml up")
            return False
    
    def execute_query(self, query: str):
        """Execute SQL query and return results"""
        if not self.conn:
            print("‚ùå Not connected to Trino. Call connect() first.")
            return None
        
        try:
            cursor = self.conn.cursor()
            cursor.execute(query)
            
            # Get column names
            columns = [desc[0] for desc in cursor.description]
            
            # Fetch all results
            results = cursor.fetchall()
            
            # Convert to DataFrame
            df = pd.DataFrame(results, columns=columns)
            
            print(f"üîç Query executed successfully!")
            print(f"üìä Returned {len(df)} rows")
            return df
            
        except Exception as e:
            print(f"‚ùå Query failed: {e}")
            return None
    
    def show_catalogs(self):
        """Show available catalogs"""
        query = "SHOW CATALOGS"
        return self.execute_query(query)
    
    def show_schemas(self, catalog: str):
        """Show schemas in catalog"""
        query = f"SHOW SCHEMAS FROM {catalog}"
        return self.execute_query(query)
    
    def show_tables(self, catalog: str, schema: str):
        """Show tables in schema"""
        query = f"SHOW TABLES FROM {catalog}.{schema}"
        return self.execute_query(query)

# Initialize Trino client
trino_client = TrinoClient()

# Try to connect to real Trino cluster
if trino_client.connect():
    print("üéâ Successfully connected to Trino cluster!")
    
    # Show available catalogs
    print("\nüìö Available Catalogs:")
    catalogs_df = trino_client.show_catalogs()
    if catalogs_df is not None:
        print(catalogs_df)
    
    # Show schemas for each catalog
    for catalog in ['mongodb', 'postgresql']:
        print(f"\nüìÅ Schemas in {catalog}:")
        schemas_df = trino_client.show_schemas(catalog)
        if schemas_df is not None:
            print(schemas_df)
else:
    print("‚ö†Ô∏è  Using simulator mode. Start Trino cluster to use real queries.")
    print("üìù Run: docker-compose -f docker-compose-trino.yml up")

‚úÖ Connected to Trino cluster at localhost:8080
üéâ Successfully connected to Trino cluster!

üìö Available Catalogs:
üîç Query executed successfully!
üìä Returned 3 rows
      Catalog
0     mongodb
1  postgresql
2      system

üìÅ Schemas in mongodb:
üîç Query executed successfully!
üìä Returned 2 rows
               Schema
0           ecommerce
1  information_schema

üìÅ Schemas in postgresql:
üîç Query executed successfully!
üìä Returned 3 rows
               Schema
0  information_schema
1          pg_catalog
2              public

## Exercise 1: Single-Source Queries

Let's start with basic queries on individual data sources to understand the data structure.

In [3]:
# Exercise 1: Single-Source Queries

# 1. Query MongoDB - Product Catalog
print("üîç Querying MongoDB - Product Catalog")
mongodb_query = """
SELECT 
    productId,
    name,
    category,
    price,
    inventory.available as available_stock,
    metadata.reviews.averageRating as rating
FROM mongodb.ecommerce.products 
WHERE category = 'electronics'
ORDER BY price DESC
LIMIT 10
"""

result1 = trino_client.execute_query(mongodb_query)
if result1 is not None:
    print("üìä MongoDB Results:")
    print(result1)
print()

# 2. Query PostgreSQL - Available Tables
print("üîç Querying PostgreSQL - Available Tables")
postgresql_query = """
SELECT table_name, table_type 
FROM postgresql.information_schema.tables 
WHERE table_schema = 'public'
ORDER BY table_name
"""

result2 = trino_client.execute_query(postgresql_query)
if result2 is not None:
    print("üìä PostgreSQL Tables:")
    print(result2)
print()

# 3. Show Available Catalogs
print("üîç Available Catalogs:")
catalogs_df = trino_client.show_catalogs()
if catalogs_df is not None:
    print("üìä Available Catalogs:")
    print(catalogs_df)
print()

# 4. Show MongoDB Schemas and Tables
print("üîç MongoDB Schema Information:")
schemas_df = trino_client.show_schemas('mongodb')
if schemas_df is not None:
    print("üìä MongoDB Schemas:")
    print(schemas_df)
    
    # Show tables in ecommerce schema
    tables_df = trino_client.show_tables('mongodb', 'ecommerce')
    if tables_df is not None:
        print("üìä MongoDB Tables in ecommerce schema:")
        print(tables_df)
print()

# 5. Show PostgreSQL Schemas and Tables
print("üîç PostgreSQL Schema Information:")
schemas_df = trino_client.show_schemas('postgresql')
if schemas_df is not None:
    print("üìä PostgreSQL Schemas:")
    print(schemas_df)
    
    # Show tables in public schema
    tables_df = trino_client.show_tables('postgresql', 'public')
    if tables_df is not None:
        print("üìä PostgreSQL Tables in public schema:")
        print(tables_df)
print()

print("‚úÖ Single-source queries completed!")

üîç Querying MongoDB - Product Catalog
üîç Query executed successfully!
üìä Returned 2 rows
üìä MongoDB Results:
  productId                name     category     price  available_stock  \
0  prod_001       iPhone 15 Pro  electronics  24000000               49
1  prod_002  Samsung Galaxy S24  electronics  22000000               29

   rating
0     4.8
1     4.6

üîç Querying PostgreSQL - Available Tables
üîç Query executed successfully!
üìä Returned 3 rows
üìä PostgreSQL Tables:
      table_name  table_type
0      customers  BASE TABLE
1  order_summary  BASE TABLE
2         orders  BASE TABLE

üîç Available Catalogs:
üîç Query executed successfully!
üìä Returned 3 rows
üìä Available Catalogs:
      Catalog
0     mongodb
1  postgresql
2      system

üîç MongoDB Schema Information:
üîç Query executed successfully!
üìä Returned 2 rows
üìä MongoDB Schemas:
               Schema
0           ecommerce
1  information_schema
üîç Query executed successfully!
üìä Returned 2 rows
üìä MongoDB Tables in ecommerce schema:
      Table
0    orders
1  products

üîç PostgreSQL Schema Information:
üîç Query executed successfully!
üìä Returned 3 rows
üìä PostgreSQL Schemas:
               Schema
0  information_schema
1          pg_catalog
2              public
üîç Query executed successfully!
üìä Returned 3 rows
üìä PostgreSQL Tables in public schema:
           Table
0      customers
1  order_summary
2         orders

‚úÖ Single-source queries completed!

## Exercise 2: Federated Queries

Now let's perform federated queries that join data across multiple sources.

## Exercise 2: Federated Queries

Now let's perform federated queries that combine data from multiple databases using Trino's distributed SQL capabilities.

In [4]:
# Exercise 2: Federated Queries

# 1. Cross-Database User Analysis
print("üîç Cross-Database User Analysis")
print("Combining MongoDB products with PostgreSQL orders")
federated_query1 = """
SELECT 
    c.customer_id,
    c.name as customer_name,
    c.customer_tier,
    COUNT(o.order_id) as total_orders,
    SUM(o.total_amount) as total_spent,
    AVG(o.total_amount) as avg_order_value,
    MAX(o.order_date) as last_order_date
FROM postgresql.public.customers c
LEFT JOIN postgresql.public.orders o ON c.customer_id = o.user_id
GROUP BY c.customer_id, c.name, c.customer_tier
ORDER BY total_spent DESC
"""

result1 = trino_client.execute_query(federated_query1)
if result1 is not None:
    print("üìä Customer Analysis Results:")
    print(result1)
print()

# 2. Product Performance Analysis
print("üîç Product Performance Analysis")
print("Combining MongoDB product catalog with PostgreSQL order data")
federated_query2 = """
SELECT 
    p.productId,
    p.name as product_name,
    p.category,
    p.price as current_price,
    p.inventory.available as available_stock,
    COUNT(o.order_id) as times_ordered,
    SUM(o.quantity) as total_quantity_sold,
    SUM(o.total_amount) as total_revenue,
    AVG(o.unit_price) as avg_selling_price
FROM mongodb.ecommerce.products p
LEFT JOIN postgresql.public.orders o ON p.productId = o.product_id
GROUP BY p.productId, p.name, p.category, p.price, p.inventory.available
ORDER BY total_revenue DESC NULLS LAST
"""

result2 = trino_client.execute_query(federated_query2)
if result2 is not None:
    print("üìä Product Performance Results:")
    print(result2)
print()

# 3. Real-time Business Intelligence Dashboard
print("üîç Real-time Business Intelligence Dashboard")
print("Comprehensive business metrics across databases")
federated_query3 = """
SELECT 
    'Total Customers' as metric_name,
    COUNT(*) as metric_value,
    'customers' as unit
FROM postgresql.public.customers
UNION ALL
SELECT 
    'Total Products' as metric_name,
    COUNT(*) as metric_value,
    'products' as unit
FROM mongodb.ecommerce.products
UNION ALL
SELECT 
    'Total Orders' as metric_name,
    COUNT(*) as metric_value,
    'orders' as unit
FROM postgresql.public.orders
UNION ALL
SELECT 
    'Total Revenue' as metric_name,
    SUM(total_amount) as metric_value,
    'VND' as unit
FROM postgresql.public.orders
UNION ALL
SELECT 
    'Average Order Value' as metric_name,
    AVG(total_amount) as metric_value,
    'VND' as unit
FROM postgresql.public.orders
UNION ALL
SELECT 
    'Gold Customers' as metric_name,
    COUNT(*) as metric_value,
    'customers' as unit
FROM postgresql.public.customers
WHERE customer_tier = 'gold'
"""

result3 = trino_client.execute_query(federated_query3)
if result3 is not None:
    print("üìä Business Intelligence Dashboard:")
    print(result3)
print()

# 4. Customer Segmentation Analysis
print("üîç Customer Segmentation Analysis")
print("Analyzing customer behavior patterns")
federated_query4 = """
SELECT 
    c.customer_tier,
    COUNT(DISTINCT c.customer_id) as customer_count,
    COUNT(o.order_id) as total_orders,
    SUM(o.total_amount) as total_revenue,
    AVG(o.total_amount) as avg_order_value,
    AVG(EXTRACT(DAY FROM CURRENT_TIMESTAMP - o.order_date)) as avg_days_since_last_order
FROM postgresql.public.customers c
LEFT JOIN postgresql.public.orders o ON c.customer_id = o.user_id
GROUP BY c.customer_tier
ORDER BY total_revenue DESC
"""

result4 = trino_client.execute_query(federated_query4)
if result4 is not None:
    print("üìä Customer Segmentation Results:")
    print(result4)
print()

print("‚úÖ Federated queries completed!")

üîç Cross-Database User Analysis
Combining MongoDB products with PostgreSQL orders
üîç Query executed successfully!
üìä Returned 5 rows
üìä Customer Analysis Results:
  customer_id  customer_name customer_tier  total_orders  total_spent  \
0    cust_001  Alice Johnson          gold             2  45000000.00
1    cust_004   David Wilson          gold             1  44000000.00
2    cust_002      Bob Smith        silver             2  37000000.00
3    cust_003    Carol Davis        bronze             1  15000000.00
4    cust_005      Eva Brown        silver             1   5000000.00

  avg_order_value     last_order_date
0     22500000.00 2025-09-17 09:15:00
1     44000000.00 2025-09-19 11:30:00
2     18500000.00 2025-09-21 08:10:00
3     15000000.00 2025-09-18 16:45:00
4      5000000.00 2025-09-20 13:20:00

üîç Product Performance Analysis
Combining MongoDB product catalog with PostgreSQL order data
üîç Query executed successfully!
üìä Returned 2 rows
üìä Product Performance Results:
  productId        product_name     category  current_price  available_stock  \
0  prod_002  Samsung Galaxy S24  electronics       22000000               29
1  prod_001       iPhone 15 Pro  electronics       24000000               49

   times_ordered  total_quantity_sold total_revenue avg_selling_price
0              2                    3   66000000.00       22000000.00
1              3                    4   60000000.00       15000000.00

üîç Real-time Business Intelligence Dashboard
Comprehensive business metrics across databases
üîç Query executed successfully!
üìä Returned 6 rows
üìä Business Intelligence Dashboard:
           metric_name  metric_value       unit
0         Total Orders          7.00     orders
1      Total Customers          5.00  customers
2       Gold Customers          2.00  customers
3  Average Order Value   20857142.86        VND
4       Total Products          2.00   products
5        Total Revenue  146000000.00        VND

üîç Customer Segmentation Analysis
Analyzing customer behavior patterns
üîç Query executed successfully!
üìä Returned 3 rows
üìä Customer Segmentation Results:
  customer_tier  customer_count  total_orders total_revenue avg_order_value  \
0          gold               2             3   89000000.00     29666666.67
1        silver               2             3   42000000.00     14000000.00
2        bronze               1             1   15000000.00     15000000.00

   avg_days_since_last_order
0                        4.0
1                        2.0
2                        3.0

‚úÖ Federated queries completed!

## Exercise 2: Federated Queries

Now let's perform federated queries that combine data from MongoDB and PostgreSQL databases.

In [5]:
# Exercise 2: Federated Queries

# 1. Cross-Database User Analysis
print("üîç Cross-Database User Analysis")
print("Combining MongoDB products with PostgreSQL orders")
federated_query1 = """
SELECT 
    c.customer_id,
    c.name as customer_name,
    c.customer_tier,
    COUNT(o.order_id) as total_orders,
    SUM(o.total_amount) as total_spent,
    AVG(o.total_amount) as avg_order_value,
    MAX(o.order_date) as last_order_date
FROM postgresql.public.customers c
LEFT JOIN postgresql.public.orders o ON c.customer_id = o.user_id
GROUP BY c.customer_id, c.name, c.customer_tier
ORDER BY total_spent DESC
"""

result1 = trino_client.execute_query(federated_query1)
if result1 is not None:
    print("üìä Customer Analysis Results:")
    print(result1)
print()

# 2. Product Performance Analysis
print("üîç Product Performance Analysis")
print("Combining MongoDB product catalog with PostgreSQL order data")
federated_query2 = """
SELECT 
    p.productId,
    p.name as product_name,
    p.category,
    p.price as current_price,
    p.inventory.available as available_stock,
    COUNT(o.order_id) as times_ordered,
    SUM(o.quantity) as total_quantity_sold,
    SUM(o.total_amount) as total_revenue,
    AVG(o.unit_price) as avg_selling_price
FROM mongodb.ecommerce.products p
LEFT JOIN postgresql.public.orders o ON p.productId = o.product_id
GROUP BY p.productId, p.name, p.category, p.price, p.inventory.available
ORDER BY total_revenue DESC NULLS LAST
"""

result2 = trino_client.execute_query(federated_query2)
if result2 is not None:
    print("üìä Product Performance Results:")
    print(result2)
print()

# 3. Real-time Business Intelligence Dashboard
print("üîç Real-time Business Intelligence Dashboard")
print("Comprehensive business metrics across databases")
federated_query3 = """
SELECT 
    'Total Customers' as metric_name,
    COUNT(*) as metric_value,
    'customers' as unit
FROM postgresql.public.customers
UNION ALL
SELECT 
    'Total Products' as metric_name,
    COUNT(*) as metric_value,
    'products' as unit
FROM mongodb.ecommerce.products
UNION ALL
SELECT 
    'Total Orders' as metric_name,
    COUNT(*) as metric_value,
    'orders' as unit
FROM postgresql.public.orders
UNION ALL
SELECT 
    'Total Revenue' as metric_name,
    SUM(total_amount) as metric_value,
    'VND' as unit
FROM postgresql.public.orders
UNION ALL
SELECT 
    'Average Order Value' as metric_name,
    AVG(total_amount) as metric_value,
    'VND' as unit
FROM postgresql.public.orders
UNION ALL
SELECT 
    'Gold Customers' as metric_name,
    COUNT(*) as metric_value,
    'customers' as unit
FROM postgresql.public.customers
WHERE customer_tier = 'gold'
"""

result3 = trino_client.execute_query(federated_query3)
if result3 is not None:
    print("üìä Business Intelligence Dashboard:")
    print(result3)
print()

# 4. Customer Segmentation Analysis
print("üîç Customer Segmentation Analysis")
print("Analyzing customer behavior patterns")
federated_query4 = """
SELECT 
    c.customer_tier,
    COUNT(DISTINCT c.customer_id) as customer_count,
    COUNT(o.order_id) as total_orders,
    SUM(o.total_amount) as total_revenue,
    AVG(o.total_amount) as avg_order_value,
    AVG(EXTRACT(DAY FROM CURRENT_TIMESTAMP - o.order_date)) as avg_days_since_last_order
FROM postgresql.public.customers c
LEFT JOIN postgresql.public.orders o ON c.customer_id = o.user_id
GROUP BY c.customer_tier
ORDER BY total_revenue DESC
"""

result4 = trino_client.execute_query(federated_query4)
if result4 is not None:
    print("üìä Customer Segmentation Results:")
    print(result4)
print()

print("‚úÖ Federated queries completed!")

üîç Cross-Database User Analysis
Combining MongoDB products with PostgreSQL orders
üîç Query executed successfully!
üìä Returned 5 rows
üìä Customer Analysis Results:
  customer_id  customer_name customer_tier  total_orders  total_spent  \
0    cust_001  Alice Johnson          gold             2  45000000.00
1    cust_004   David Wilson          gold             1  44000000.00
2    cust_002      Bob Smith        silver             2  37000000.00
3    cust_003    Carol Davis        bronze             1  15000000.00
4    cust_005      Eva Brown        silver             1   5000000.00

  avg_order_value     last_order_date
0     22500000.00 2025-09-17 09:15:00
1     44000000.00 2025-09-19 11:30:00
2     18500000.00 2025-09-21 08:10:00
3     15000000.00 2025-09-18 16:45:00
4      5000000.00 2025-09-20 13:20:00

üîç Product Performance Analysis
Combining MongoDB product catalog with PostgreSQL order data
üîç Query executed successfully!
üìä Returned 2 rows
üìä Product Performance Results:
  productId        product_name     category  current_price  available_stock  \
0  prod_002  Samsung Galaxy S24  electronics       22000000               29
1  prod_001       iPhone 15 Pro  electronics       24000000               49

   times_ordered  total_quantity_sold total_revenue avg_selling_price
0              2                    3   66000000.00       22000000.00
1              3                    4   60000000.00       15000000.00

üîç Real-time Business Intelligence Dashboard
Comprehensive business metrics across databases
üîç Query executed successfully!
üìä Returned 6 rows
üìä Business Intelligence Dashboard:
           metric_name  metric_value       unit
0        Total Revenue  146000000.00        VND
1       Gold Customers          2.00  customers
2      Total Customers          5.00  customers
3         Total Orders          7.00     orders
4       Total Products          2.00   products
5  Average Order Value   20857142.86        VND

üîç Customer Segmentation Analysis
Analyzing customer behavior patterns
üîç Query executed successfully!
üìä Returned 3 rows
üìä Customer Segmentation Results:
  customer_tier  customer_count  total_orders total_revenue avg_order_value  \
0          gold               2             3   89000000.00     29666666.67
1        silver               2             3   42000000.00     14000000.00
2        bronze               1             1   15000000.00     15000000.00

   avg_days_since_last_order
0                        4.0
1                        2.0
2                        3.0

‚úÖ Federated queries completed!

## Exercise 3: Data Lakehouse Analytics

Advanced analytics using Trino's capabilities for data lakehouse scenarios with MongoDB and PostgreSQL.

In [11]:
# Exercise 3: Data Lakehouse Analytics

# 1. Time-Series Analysis
print("üîç Time-Series Analysis")
print("Analyzing order trends over time")
timeseries_query = """
WITH daily_metrics AS (
    SELECT 
        DATE_TRUNC('day', order_date) as order_day,
        COUNT(DISTINCT user_id) as unique_customers,
        COUNT(*) as total_orders,
        SUM(total_amount) as daily_revenue,
        AVG(total_amount) as avg_order_value
    FROM postgresql.public.orders
    WHERE order_date >= CURRENT_DATE - INTERVAL '30' DAY
    GROUP BY DATE_TRUNC('day', order_date)
)
SELECT 
    order_day,
    unique_customers,
    total_orders,
    daily_revenue,
    avg_order_value,
    -- Calculate growth rates
    LAG(daily_revenue) OVER (ORDER BY order_day) as prev_day_revenue,
    CASE 
        WHEN LAG(daily_revenue) OVER (ORDER BY order_day) > 0 
        THEN (daily_revenue - LAG(daily_revenue) OVER (ORDER BY order_day)) / 
             LAG(daily_revenue) OVER (ORDER BY order_day) * 100 
        ELSE 0 
    END as revenue_growth_pct
FROM daily_metrics
ORDER BY order_day DESC
"""

result1 = trino_client.execute_query(timeseries_query)
if result1 is not None:
    print("üìä Time-Series Analysis Results:")
    print(result1)
print()

# 2. Customer Segmentation Analysis
print("üîç Customer Segmentation Analysis")
print("Analyzing customer behavior patterns")
segmentation_query = """
WITH customer_metrics AS (
    SELECT 
        c.customer_id,
        c.name as customer_name,
        c.customer_tier,
        -- Purchase behavior
        COUNT(DISTINCT o.order_id) as order_frequency,
        SUM(o.total_amount) as total_spent,
        AVG(o.total_amount) as avg_order_value,
        MAX(o.order_date) as last_order_date,
        -- Days since last order
        EXTRACT(DAY FROM CURRENT_TIMESTAMP - MAX(o.order_date)) as days_since_last_order
    FROM postgresql.public.customers c
    LEFT JOIN postgresql.public.orders o ON c.customer_id = o.user_id
    GROUP BY c.customer_id, c.name, c.customer_tier
),
customer_segments AS (
    SELECT 
        customer_id,
        customer_name,
        customer_tier,
        order_frequency,
        total_spent,
        avg_order_value,
        days_since_last_order,
        -- RFM Analysis
        CASE 
            WHEN total_spent >= 30000000 THEN 'High Value'
            WHEN total_spent >= 15000000 THEN 'Medium Value'
            ELSE 'Low Value'
        END as value_segment,
        CASE 
            WHEN order_frequency >= 3 THEN 'Frequent'
            WHEN order_frequency >= 2 THEN 'Regular'
            ELSE 'Occasional'
        END as frequency_segment,
        CASE 
            WHEN days_since_last_order <= 7 THEN 'Recent'
            WHEN days_since_last_order <= 30 THEN 'Active'
            ELSE 'Inactive'
        END as recency_segment
    FROM customer_metrics
)
SELECT 
    value_segment,
    frequency_segment,
    recency_segment,
    COUNT(*) as customer_count,
    AVG(total_spent) as avg_total_spent,
    AVG(order_frequency) as avg_order_frequency,
    AVG(days_since_last_order) as avg_days_since_last_order
FROM customer_segments
GROUP BY value_segment, frequency_segment, recency_segment
ORDER BY avg_total_spent DESC
"""

result2 = trino_client.execute_query(segmentation_query)
if result2 is not None:
    print("üìä Customer Segmentation Results:")
    print(result2)
print()

# 3. Product Performance Analytics
print("üîç Product Performance Analytics")
print("Analyzing product performance and inventory")
product_analytics_query = """
WITH product_performance AS (
    SELECT 
        p.productId,
        p.name,
        p.category,
        p.price,
        p.inventory.available as current_stock,
        p.metadata.reviews.averageRating as rating,
        -- Sales performance
        COUNT(DISTINCT o.order_id) as times_ordered,
        SUM(o.quantity) as total_quantity_sold,
        SUM(o.total_amount) as total_revenue,
        AVG(o.unit_price) as avg_selling_price,
        -- Inventory turnover
        CASE 
            WHEN p.inventory.available > 0 
            THEN SUM(o.quantity) / p.inventory.available 
            ELSE 0 
        END as inventory_turnover_ratio
    FROM mongodb.ecommerce.products p
    LEFT JOIN postgresql.public.orders o ON p.productId = o.product_id
    GROUP BY p.productId, p.name, p.category, p.price, p.inventory.available, p.metadata.reviews.averageRating
),
product_insights AS (
    SELECT 
        productId,
        name,
        category,
        price,
        current_stock,
        rating,
        times_ordered,
        total_quantity_sold,
        total_revenue,
        avg_selling_price,
        inventory_turnover_ratio,
        -- Performance categories
        CASE 
            WHEN total_revenue >= 50000000 THEN 'Top Performer'
            WHEN total_revenue >= 20000000 THEN 'Good Performer'
            WHEN total_revenue >= 10000000 THEN 'Average Performer'
            ELSE 'Low Performer'
        END as performance_category,
        -- Stock status
        CASE 
            WHEN current_stock <= 10 THEN 'Low Stock'
            WHEN current_stock <= 30 THEN 'Medium Stock'
            ELSE 'High Stock'
        END as stock_status,
        -- Recommendation
        CASE 
            WHEN current_stock <= 10 AND times_ordered >= 2 THEN 'URGENT: Restock'
            WHEN current_stock <= 30 AND times_ordered >= 1 THEN 'Restock Soon'
            WHEN times_ordered = 0 AND current_stock > 20 THEN 'Consider Promotion'
            ELSE 'Monitor'
        END as recommended_action
    FROM product_performance
)
SELECT 
    productId,
    name,
    category,
    price,
    current_stock,
    rating,
    performance_category,
    stock_status,
    recommended_action,
    times_ordered,
    total_revenue,
    inventory_turnover_ratio
FROM product_insights
ORDER BY 
    CASE recommended_action
        WHEN 'URGENT: Restock' THEN 1
        WHEN 'Restock Soon' THEN 2
        WHEN 'Consider Promotion' THEN 3
        ELSE 4
    END,
    total_revenue DESC
"""

result3 = trino_client.execute_query(product_analytics_query)
if result3 is not None:
    print("üìä Product Performance Analytics Results:")
    print(result3)
print()

print("‚úÖ Data lakehouse analytics completed!")

üîç Time-Series Analysis
Analyzing order trends over time
üîç Query executed successfully!
üìä Returned 7 rows
üìä Time-Series Analysis Results:
   order_day  unique_customers  total_orders daily_revenue avg_order_value  \
0 2025-09-21                 1             1   15000000.00     15000000.00
1 2025-09-20                 1             1    5000000.00      5000000.00
2 2025-09-19                 1             1   44000000.00     44000000.00
3 2025-09-18                 1             1   15000000.00     15000000.00
4 2025-09-17                 1             1   15000000.00     15000000.00
5 2025-09-16                 1             1   22000000.00     22000000.00
6 2025-09-15                 1             1   30000000.00     30000000.00

  prev_day_revenue revenue_growth_pct
0       5000000.00             200.00
1      44000000.00             -89.00
2      15000000.00             193.00
3      15000000.00               0.00
4      22000000.00             -32.00
5      30000000.00             -27.00
6             None               0.00

üîç Customer Segmentation Analysis
Analyzing customer behavior patterns
üîç Query executed successfully!
üìä Returned 4 rows
üìä Customer Segmentation Results:
  value_segment frequency_segment recency_segment  customer_count  \
0    High Value        Occasional          Recent               1
1    High Value           Regular          Recent               2
2  Medium Value        Occasional          Recent               1
3     Low Value        Occasional          Recent               1

  avg_total_spent  avg_order_frequency  avg_days_since_last_order
0     44000000.00                  1.0                        2.0
1     41000000.00                  2.0                        2.0
2     15000000.00                  1.0                        3.0
3      5000000.00                  1.0                        1.0

üîç Product Performance Analytics
Analyzing product performance and inventory
üîç Query executed successfully!
üìä Returned 2 rows
üìä Product Performance Analytics Results:
  productId                name     category     price  current_stock  rating  \
0  prod_002  Samsung Galaxy S24  electronics  22000000             29     4.6
1  prod_001       iPhone 15 Pro  electronics  24000000             49     4.8

  performance_category  stock_status recommended_action  times_ordered  \
0        Top Performer  Medium Stock       Restock Soon              2
1        Top Performer    High Stock            Monitor              3

  total_revenue  inventory_turnover_ratio
0   66000000.00                         0
1   60000000.00                         0

‚úÖ Data lakehouse analytics completed!